# Generated by Django 4.2.13 on 2024-05-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=30)),
                ('fin_prdt_nm', models.CharField(max_length=50)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('join_way', models.TextField()),
                ('crdt_prdt_type', models.CharField(max_length=30)),
                ('crdt_prdt_type_nm', models.CharField(max_length=50)),
                ('cb_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=30)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('crdt_lend_rate_type', models.CharField(max_length=30)),
                ('crdt_lend_rate_type_nm', models.CharField(max_length=50)),
                ('crdt_grad_1', models.FloatField(max_length=10, null=True)),
                ('crdt_grad_4', models.FloatField(max_length=10, null=True)),
                ('crdt_grad_5', models.FloatField(max_length=10, null=True)),
                ('crdt_grad_6', models.FloatField(max_length=10, null=True)),
                ('crdt_grad_10', models.FloatField(max_length=10, null=True)),
                ('crdt_grad_11', models.FloatField(max_length=10, null=True)),
                ('crdt_grad_12', models.FloatField(max_length=10, null=True)),
                ('crdt_grad_13', models.FloatField(max_length=10, null=True)),
                ('crdt_grad_avg', models.FloatField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fin_prdt_nm', models.CharField(max_length=50)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('join_way', models.TextField()),
                ('mtrt_int', models.CharField(max_length=200)),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.IntegerField()),
                ('join_member', models.CharField(max_length=100)),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fin_prdt_nm', models.CharField(max_length=50)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('join_way', models.TextField()),
                ('mtrt_int', models.CharField(max_length=200)),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.IntegerField()),
                ('join_member', models.CharField(max_length=100)),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=30)),
                ('intr_rate_type_nm', models.CharField(max_length=50)),
                ('rsrv_type', models.CharField(max_length=30)),
                ('rsrv_type_nm', models.CharField(max_length=50)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField(max_length=10)),
                ('intr_rate2', models.FloatField(max_length=10)),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.saving')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=30)),
                ('intr_rate_type_nm', models.CharField(max_length=50)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField(max_length=10)),
                ('intr_rate2', models.FloatField(max_length=10)),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.deposit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='creditloan',
            constraint=models.UniqueConstraint(fields=('fin_prdt_cd', 'fin_co_no'), name='unique_creditloan'),
        ),
    ]
