# Generated by Django 5.0.6 on 2024-05-16 05:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('birthday', models.CharField(blank=True, max_length=8, null=True)),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=10, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('asset', models.IntegerField(null=True)),
                ('debt', models.IntegerField(null=True)),
                ('period', models.CharField(choices=[('1년 이하', '1년 이하'), ('1년 초과 ~ 2년 이하', '1년 초과 ~ 2년 이하'), ('2년 초과 ~ 3년 이하', '2년 초과 ~ 3년 이하')], max_length=20, null=True)),
                ('bank', models.CharField(choices=[('우리은행', '우리은행'), ('한국스탠다드차타드은행', '한국스탠다드차타드은행'), ('대구은행', '대구은행'), ('부산은행', '부산은행'), ('광주은행', '광주은행'), ('제주은행', '제주은행'), ('전북은행', '전북은행'), ('경남은행', '경남은행'), ('중소기업은행', '중소기업은행'), ('한국산업은행', '한국산업은행'), ('국민은행', '국민은행'), ('신한은행', '신한은행'), ('농협은행', '농협은행'), ('KEB하나은행', 'KEB하나은행'), ('수협은행', '수협은행'), ('주식회사 카카오뱅크', '주식회사 카카오뱅크'), ('주식회사 케이뱅크', '주식회사 케이뱅크'), ('토스뱅크 주식회사', '토스뱅크 주식회사'), ('기타', '기타')], max_length=20, null=True)),
            ],
        ),
    ]
