# Generated by Django 5.0.6 on 2024-05-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailuser',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
