# Generated by Django 5.0.6 on 2024-05-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_detailuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
