# Generated by Django 4.2.13 on 2024-05-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=2),
        ),
    ]
