# Generated by Django 4.2.13 on 2024-05-20 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_article_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
