# Generated by Django 4.2.13 on 2024-05-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('공지사항', '공지사항'), ('자유게시판', '자유게시판')], max_length=20),
        ),
    ]
